import { GetStaticProps, GetStaticPaths } from "next";
import Head from "next/head";

import type { NextPage } from "next";
import { searchProducts, Product } from "@lib/db";

import ProductSmall from "@components/products/productSmall";

type StaticProps = {
  query: string;
  products: Product[];
};

const ProductPage: NextPage<StaticProps> = ({ query, products }) => {
  return (
    <>
      <Head>
        <title>Sebbes ekologiska - {query}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="lg:px-12 py-4 lg:py-8">
        <div className="flex flex-wrap gap-10 justify-center">
          {products.length === 0 && (
            <p className="bg-white rounded-lg border-green-300 border py-2 px-4 max-w-md">
              Vi har tyvärr inte några resultat för den här sökningen. Men
              kontakta oss gärna på{" "}
              <a href="mailto:kontakt@sebbeseko.se" className="text-green-500">
                kontakt@sebbeseko.se
              </a>{" "}
              om det är något du saknar!
            </p>
          )}
          {products.map((product) => {
            return <ProductSmall key={product.id} product={product} />;
          })}
        </div>
      </main>
    </>
  );
};

export const getStaticPaths: GetStaticPaths = async () => {
  return {
    paths: [],
    fallback: "blocking",
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  if (!(params && params.query && typeof params.query === "string")) {
    return { notFound: true };
  }
  const { query } = params;

  try {
    const products = await searchProducts(query);
    console.log(products);
    return {
      props: { query, products },
      revalidate: 5,
    };
  } catch (error) {
    console.log("sok", error);
    return { notFound: true };
  }
};

export default ProductPage;
