import { GetStaticProps, GetStaticPaths } from "next";
import Head from "next/head";

import type { NextPage } from "next";
import { getProductById, Product } from "@lib/db";
import ProductComponent from "@components/products/product";

type StaticProps = {
  product: Product;
};

const ProductPage: NextPage<StaticProps> = ({ product }) => {
  return (
    <>
      <Head>
        <title>Sebbes ekologiska - {product.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex py-2 lg:py-8 lg:px-12 justify-center">
        <ProductComponent product={product} />
      </main>
    </>
  );
};

export const getStaticPaths: GetStaticPaths = async () => {
  return {
    paths: [],
    fallback: "blocking",
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  if (!(params && params.product && typeof params.product === "string")) {
    return { notFound: true };
  }

  let product = await getProductById(params.product);
  if (product === undefined) {
    return { notFound: true };
  }

  return {
    props: { product },
    revalidate: 60,
  };
};

export default ProductPage;
