import { GetStaticProps, GetStaticPaths } from "next";
import Head from "next/head";

import type { NextPage } from "next";
import type { Product } from "@lib/types";

type StaticProps = {
  product: Product;
};

const Product: NextPage<StaticProps> = ({ product }) => {
  return (
    <>
      <Head>
        <title>Sebbes butik - {product}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Produkt: {product}</div>
    </>
  );
};

export const getStaticPaths: GetStaticPaths = async () => {
  return {
    paths: [],
    fallback: "blocking",
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  if (!(params && params.product)) {
    return { notFound: true };
  }

  // Fetch data from DB.

  return {
    props: { product: params.product },
    revalidate: 60,
  };
};

export default Product;
