import { NextPage } from "next";
import Head from "next/head";
import AddProduct from "@components/products/addProductPage";

const AddProductPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Sebbes butik - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AddProduct />
    </>
  );
};

export default AddProductPage;
