import { GetStaticProps, GetStaticPaths } from "next";
import Head from "next/head";
import type { NextPage } from "next";

import Layout from "@components/layout/store";

type StaticProps = {
  category: string;
};

const Category: NextPage<StaticProps> = ({ category }) => {
  return (
    <>
      <Head>
        <title>Sebbes butik - {category}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>Kategori: {category}</Layout>
    </>
  );
};

export const getStaticPaths: GetStaticPaths = async () => {
  return {
    paths: [],
    fallback: "blocking",
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  if (!(params && params.category)) {
    return { notFound: true };
  }

  // Fetch data from DB.

  return {
    props: { category: params.category },
    revalidate: 60,
  };
};

export default Category;
