import { GetStaticProps, GetStaticPaths } from "next";
import Head from "next/head";

import ProductSmall from "@components/products/product_small";

import type { NextPage } from "next";
import type { Product } from "@lib/types";
import { getProductsByCategory } from "@lib/db";

type StaticProps = {
  category: string;
  products: Product[];
};

const Category: NextPage<StaticProps> = ({ category, products }) => {
  return (
    <>
      <Head>
        <title>Sebbes butik - {category}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {products.map((product) => {
          return <ProductSmall key={product.id} product={product} />;
        })}
      </div>
    </>
  );
};

export const getStaticPaths: GetStaticPaths = async () => {
  return {
    paths: [],
    fallback: "blocking",
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  if (!(params && params.category && typeof params.category === "string")) {
    return { notFound: true };
  }
  // Fetch data from DB.
  const products = await getProductsByCategory(params.category);
  return {
    props: { products },
    revalidate: 60,
  };
};

export default Category;
