import { GetStaticProps, GetStaticPaths } from "next";
import Head from "next/head";

import ProductSmall from "@components/products/productSmall";

import type { NextPage } from "next";
import { getProductsByCategory, Product } from "@lib/db";

type StaticProps = {
  category: string;
  products: Product[];
};

const Category: NextPage<StaticProps> = ({ category, products }) => {
  return (
    <>
      <Head>
        <title>Sebbes ekologiska - {category}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-12 py-4 lg:py-8">
        <div className="flex flex-wrap gap-10 justify-center">
          {products.map((product) => (
            <ProductSmall key={product.id} product={product} />
          ))}
        </div>
      </main>
    </>
  );
};

export const getStaticPaths: GetStaticPaths = async () => {
  return {
    paths: [],
    fallback: "blocking",
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  if (!(params && params.category && typeof params.category === "string")) {
    return { notFound: true };
  }

  const products = await getProductsByCategory(params.category);

  return {
    props: { products },
    revalidate: 60,
  };
};

export default Category;
