import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { getAllOrders, getOrdersByUserId, Order } from "@lib/db";
import Table from "@components/order/table";
import { withIronSessionSsr } from "iron-session/next";
import { sessionOptions } from "@lib/session";

type SSRProps = {
  orders: Order[];
};

const OrderPage: NextPage<SSRProps> = ({ orders }) => {
  return (
    <>
      <Head>
        <title>Sebbes butik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="lg:px-12 py-6 lg:py-8">
        <div className="flex flex-col gap-10 justify-center">
          <Table data={orders} />
        </div>
      </main>
    </>
  );
};

const getServerSidePropsNext: GetServerSideProps = async ({ req }) => {
  if (!(req.session.user && req.session.user.id)) {
    return { notFound: true };
  }

  let orders;
  // if the logged in user is admin, gets access to all orders.
  if (req.session.user.isAdmin) {
    orders = await getAllOrders();
  } else {
    orders = await getOrdersByUserId(req.session.user.id);
  }

  if (!orders) {
    return { notFound: true };
  }

  return {
    props: { orders },
  };
};

export const getServerSideProps = withIronSessionSsr(
  getServerSidePropsNext,
  sessionOptions
);

export default OrderPage;
