import { NextPage } from "next";
import Head from "next/head";

import RegisterPage from "@components/user/registerPage";

const MemberPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Sebbes ekologiska - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RegisterPage />
    </>
  );
};

export default MemberPage;
