import { GetStaticProps } from "next";
import Head from "next/head";

import ProductSmall from "@components/products/product_small";

import type { NextPage } from "next";
import type { Product } from "@lib/types";

import { getProductsAll } from "@lib/db";

type StaticProps = {
  products: Product[];
};

const Home: NextPage<StaticProps> = ({ products }) => {
  return (
    <>
      <Head>
        <title>Sebbes butik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="lg:px-12 py-4 lg:py-8">
        <div className="flex flex-wrap gap-10 justify-center">
          {products.map((product) => {
            return <ProductSmall key={product.id} product={product} />;
          })}
        </div>
      </main>
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  // Fetch data from DB.
  const products = await getProductsAll();
  return {
    props: { products },
    revalidate: 60,
  };
};

export default Home;
