import Head from "next/head";
import type { NextPage } from "next";

import Layout from "@components/layout/store";

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>Sebbes butik - Om oss</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout></Layout>
    </>
  );
};

export default About;
