import Head from "next/head";
import type { NextPage } from "next";

import Layout from "@components/layout/store";

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>Sebbes butik - Om oss</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout></Layout>
      <center>
      <h2>Who are we</h2>
      <p>We are three very eco friendly individuals who like nature and peace. <br></br>
      In our spare time we like to meditate and cook food outdoors in the nature,<br></br> 
      and that is was what lead us into the eco food industry. We want to create <br></br>
      a hub all over the world where all people have access to cheap GMO free food,<br></br>
      that's our goal, that's our mission, that's our lifestyle!</p>
      </center>
    </>
  );
};

export default About;
