import { GetStaticProps } from "next";
import Head from "next/head";
import type { NextPage } from "next";
import { getProducersAll, Producer } from "@lib/db/producer";
import React from "react";
import Image from "next/image";
import Link from "next/link";
import { cutoff } from "@lib/util";
import { LocationMarkerIcon, MailIcon } from "@heroicons/react/outline";

type StaticProps = {
  producers: Producer[];
};

const Producenter: NextPage<StaticProps> = ({ producers }) => {
  return (
    <>
      <Head>
        <title>Sebbes ekologiska</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-8 py-12">
        <div className="text-center pb-12">
          <h2 className="text-base font-bold text-green-600">
            Vi har har dom bästa ekologiska produkterna
          </h2>
          <h1 className="font-bold text-3xl md:text-4xl lg:text-5xl font-heading text-green">
            Här är våra fantastiska producenter
          </h1>
        </div>

        <section className="flex gap-8 justify-center">
          {producers.map((producer) => (
            <div
              key={producer.id}
              className="max-w-sm bg-white rounded-lg shadow-lg overflow-hidden"
            >
              <Link href={`/producent/${producer.id}`}>
                <a>
                  <Image
                    width={384}
                    height={224}
                    className="object-cover object-center"
                    src={producer.image_url}
                    alt={producer.name}
                  />
                </a>
              </Link>

              <div className="flex flex-col gap-2 px-6 py-4">
                <Link href={`/producent/${producer.id}`}>
                  <a className="text-xl font-semibold text-gray-800 hover:text-green-500">
                    {producer.name}
                  </a>
                </Link>
                <p className="text-gray-700">
                  {cutoff(producer.description, 80)}
                </p>
                <div className="flex items-center text-gray-700">
                  <LocationMarkerIcon className="w-6 h-6 text-green-400" />
                  <h3 className="px-2 text-sm">{producer.location}</h3>
                </div>
                <div className="flex items-center text-gray-700">
                  <MailIcon className="w-6 h-6 text-green-400" />
                  <h3 className="px-2 text-sm">{producer.contact}</h3>
                </div>
              </div>
            </div>
          ))}
        </section>
      </main>
    </>
  );
};

export default Producenter;

export const getStaticProps: GetStaticProps = async () => {
  const producers = await getProducersAll();
  // If we cannot fetch these (i.e. at build time) then skip.
  if (producers.length === 0) {
    return { notFound: true };
  }

  return {
    props: { producers },
    revalidate: 60,
  };
};
