import { GetStaticProps } from "next";
import Head from "next/head";
import type { NextPage } from "next";
import { getProducersAll, Producer } from "@lib/db/producer";
import React from "react";
import Image from "next/image";
import Link from "next/link";

type StaticProps = {
  producers: Producer[];
};

const Producenter: NextPage<StaticProps> = ({ producers }) => {
  return (
    <>
      <Head>
        <title>Sebbes ekologiska</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="lg:px-12 py-4 lg:py-8">
        <div className="w-full bg-white-800">
          <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-4 py-12">
            <div className="text-center pb-12">
              <h2 className="text-base font-bold text-green-600">
                Vi har har dom bästa ekologiska produkterna
              </h2>
              <h1 className="font-bold text-3xl md:text-4xl lg:text-5xl font-heading text-green">
                Här är våra fantastiska producenter
              </h1>
            </div>

            <div className="w-full bg-green-600 rounded-lg sahdow-lg  gap-5 p-12 flex flex-row justify-center items-center">
              {producers.map((producer) => {
                return (
                  <>
                    <div className="w-full bg-green-400 gap-5 rounded-lg sahdow-lg p-12 flex flex-col justify-center items-center">
                      <div className="w-36 h-36 rounded-l-lg overflow-hidden relative">
                        <Image
                          src={producer.image_url}
                          alt={producer.name}
                          layout="fill"
                          className=""
                        />
                      </div>
                      <div className="text-center">
                        <Link href={`/producent/${producer.id}`}>
                          <a>
                            <p className="text-xl text-gray-900 font-bold mb-2">
                              {producer.name}
                            </p>
                          </a>
                        </Link>
                        <p className="text-base text-gray-900 font-normal">
                          Certifierad ekologisk verksamhet
                        </p>
                      </div>{" "}
                    </div>
                  </>
                );
              })}
            </div>
          </section>
        </div>
      </main>
    </>
  );
};

export default Producenter;

export const getStaticProps: GetStaticProps = async () => {
  const producers = await getProducersAll();
  // If we cannot fetch these (i.e. at build time) then skip.
  if (producers.length === 0) {
    return { notFound: true };
  }

  return {
    props: { producers },
    revalidate: 60,
  };
};
